import type { Task, Project, Resource, TimeEntry } from './types'

const today = new Date()
const yesterday = new Date(today); yesterday.setDate(today.getDate() - 1)
const tomorrow = new Date(today); tomorrow.setDate(today.getDate() + 1)
const nextWeek = new Date(today); nextWeek.setDate(today.getDate() + 7)
const lastWeek = new Date(today); lastWeek.setDate(today.getDate() - 7)
const twoDaysAgo = new Date(today); twoDaysAgo.setDate(today.getDate() - 2)

function d(date: Date) { return date.toISOString() }

export const DEMO_USER = {
  id: 'demo-user-001',
  email: 'demo@flowki.app',
  user_metadata: {
    name: 'Aaron',
    avatar_url: '',
    has_seen_avatar: true,
    has_seen_onboarding: true,
  },
}

export const DEMO_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'Website Redesign',
    description: 'Complete overhaul of the marketing website with new brand identity',
    metadata: { icon: 'Globe', color: 'bg-blue-500', order: 0 },
    created_at: d(lastWeek),
  },
  {
    id: 'proj-2',
    name: 'Mobile App v2',
    description: 'React Native app with offline support and push notifications',
    metadata: { icon: 'Rocket', color: 'bg-violet-500', order: 1 },
    created_at: d(lastWeek),
  },
  {
    id: 'proj-section-1',
    name: 'Personal',
    metadata: { type: 'section', order: 2 },
    created_at: d(lastWeek),
  },
  {
    id: 'proj-3',
    name: 'Learning Goals',
    description: 'Books, courses, and skills to develop this quarter',
    metadata: { icon: 'Book', color: 'bg-amber-500', order: 3 },
    created_at: d(twoDaysAgo),
  },
  {
    id: 'proj-4',
    name: 'Side Project',
    description: 'Open source CLI tool for developer productivity',
    metadata: { icon: 'Code', color: 'bg-emerald-500', order: 4 },
    created_at: d(yesterday),
  },
]

export const DEMO_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Design new homepage hero section',
    description: 'Create a compelling hero with animated illustrations',
    status: 'In Progress',
    tags: [],
    dueDate: d(today),
    assignees: [],
    order: 0,
    project: 'Website Redesign',
    waitingFor: [
      { id: 'wf-1', title: 'Brand guidelines from design team', completed: true },
      { id: 'wf-2', title: 'Copy from marketing', completed: false },
    ],
  },
  {
    id: 'task-2',
    title: 'Implement responsive navigation',
    description: 'Mobile hamburger menu with smooth transitions',
    status: 'Review',
    tags: [],
    dueDate: d(yesterday),
    assignees: [],
    order: 1,
    project: 'Website Redesign',
  },
  {
    id: 'task-3',
    title: 'Set up CI/CD pipeline',
    description: 'GitHub Actions for automated testing and deployment',
    status: 'Done',
    tags: [],
    dueDate: d(twoDaysAgo),
    assignees: [],
    order: 2,
    project: 'Website Redesign',
  },
  {
    id: 'task-4',
    title: 'Write API documentation',
    description: 'OpenAPI spec for all REST endpoints',
    status: 'Backlog',
    tags: [],
    dueDate: d(nextWeek),
    assignees: [],
    order: 3,
    project: 'Website Redesign',
  },
  {
    id: 'task-5',
    title: 'Build offline sync engine',
    description: 'SQLite local storage with conflict resolution',
    status: 'In Progress',
    tags: [],
    dueDate: d(tomorrow),
    assignees: [],
    order: 4,
    project: 'Mobile App v2',
    waitingFor: [
      { id: 'wf-3', title: 'Database schema finalized', completed: false },
    ],
  },
  {
    id: 'task-6',
    title: 'Push notification service',
    description: 'Firebase Cloud Messaging integration',
    status: 'Backlog',
    tags: [],
    dueDate: d(nextWeek),
    assignees: [],
    order: 5,
    project: 'Mobile App v2',
  },
  {
    id: 'task-7',
    title: 'User onboarding flow',
    description: 'Animated walkthrough for first-time users',
    status: 'In Progress',
    tags: [],
    dueDate: d(today),
    assignees: [],
    order: 6,
    project: 'Mobile App v2',
  },
  {
    id: 'task-8',
    title: 'Read "Designing Data-Intensive Applications"',
    description: 'Chapter 5-8 this week',
    status: 'In Progress',
    tags: [],
    dueDate: d(nextWeek),
    assignees: [],
    order: 7,
    project: 'Learning Goals',
  },
  {
    id: 'task-9',
    title: 'Complete Rust fundamentals course',
    description: '',
    status: 'Backlog',
    tags: [],
    dueDate: '',
    assignees: [],
    order: 8,
    project: 'Learning Goals',
  },
  {
    id: 'task-10',
    title: 'Set up project scaffolding',
    description: 'Cargo workspace with CLI and library crates',
    status: 'Done',
    tags: [],
    dueDate: d(yesterday),
    assignees: [],
    order: 9,
    project: 'Side Project',
  },
  {
    id: 'task-11',
    title: 'Implement argument parser',
    description: 'Use clap for CLI argument handling',
    status: 'In Progress',
    tags: [],
    dueDate: d(today),
    assignees: [],
    order: 10,
    project: 'Side Project',
  },
  {
    id: 'task-12',
    title: 'Review quarterly OKRs',
    description: '',
    status: 'Backlog',
    tags: [],
    dueDate: d(today),
    assignees: [],
    order: 11,
  },
  {
    id: 'task-13',
    title: 'Schedule dentist appointment',
    description: '',
    status: 'Backlog',
    tags: [],
    dueDate: d(yesterday),
    assignees: [],
    order: 12,
  },
]

export const DEMO_RESOURCES: Resource[] = [
  {
    id: 'res-1',
    type: 'Project Note',
    title: 'Website Redesign — Architecture Notes',
    content: '<p>Key decisions:</p><ul><li>Next.js 14 with App Router</li><li>Tailwind CSS for styling</li><li>Vercel for hosting</li></ul><p>Performance target: LCP under 2.5s on mobile.</p>',
    projectId: 'Website Redesign',
    createdAt: d(lastWeek),
    pinned: true,
    order: 0,
  },
  {
    id: 'res-2',
    type: 'Meeting Note',
    title: 'Sprint Planning — Feb 20',
    content: '<p>Discussed priorities for the next two weeks. Focus areas:</p><ol><li>Homepage redesign</li><li>Navigation overhaul</li><li>Performance audit</li></ol>',
    projectId: 'Website Redesign',
    createdAt: d(twoDaysAgo),
    pinned: false,
    order: 1,
    metadata: {
      actionItems: [
        { id: 'ai-1', title: 'Share Figma mockups with team', completed: true },
        { id: 'ai-2', title: 'Set up staging environment', completed: false },
      ],
    },
  },
  {
    id: 'res-3',
    type: 'Research',
    title: 'Offline-First Architecture Patterns',
    content: '<p>Research on offline-first patterns for the mobile app:</p><ul><li>CRDTs for conflict resolution</li><li>SQLite with WAL mode for local storage</li><li>Background sync with exponential backoff</li></ul>',
    projectId: 'Mobile App v2',
    createdAt: d(yesterday),
    pinned: true,
    order: 2,
  },
  {
    id: 'res-4',
    type: 'Link',
    title: 'React Native Performance Guide',
    content: 'https://reactnative.dev/docs/performance',
    projectId: 'Mobile App v2',
    createdAt: d(yesterday),
    pinned: false,
    order: 3,
  },
  {
    id: 'res-5',
    type: 'Project Note',
    title: 'Q1 Learning Plan',
    content: '<p>Focus areas this quarter:</p><ul><li>Systems programming (Rust)</li><li>Distributed systems</li><li>Advanced TypeScript patterns</li></ul>',
    createdAt: d(lastWeek),
    pinned: false,
    order: 4,
  },
]

export const DEMO_TIME_ENTRIES: TimeEntry[] = [
  {
    id: 'te-1',
    label: 'Homepage design session',
    duration: 5400,
    startTime: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 9, 0).toISOString(),
    endTime: new Date(today.getFullYear(), today.getMonth(), today.getDate(), 10, 30).toISOString(),
    createdAt: d(today),
  },
  {
    id: 'te-2',
    label: 'Code review',
    duration: 2700,
    startTime: new Date(yesterday.getFullYear(), yesterday.getMonth(), yesterday.getDate(), 14, 0).toISOString(),
    endTime: new Date(yesterday.getFullYear(), yesterday.getMonth(), yesterday.getDate(), 14, 45).toISOString(),
    createdAt: d(yesterday),
  },
  {
    id: 'te-3',
    label: 'Reading DDIA Chapter 6',
    duration: 3600,
    startTime: new Date(yesterday.getFullYear(), yesterday.getMonth(), yesterday.getDate(), 20, 0).toISOString(),
    endTime: new Date(yesterday.getFullYear(), yesterday.getMonth(), yesterday.getDate(), 21, 0).toISOString(),
    createdAt: d(yesterday),
  },
]
